//! Generates `desktop/src/generated.ts` from the DTO types.
//!
//! The frontend used to hand-mirror ~32 interfaces against these structs, kept
//! in step only by `#[serde(rename_all = "camelCase")]` and care. Now the Rust
//! types are the single source of truth and the check is mechanical: CI runs
//! `cargo test -p azdocs-desktop` and then `git diff --exit-code`, so a field
//! added, removed or renamed here fails the build until the file is regenerated.
//!
//! Not every TypeScript type is generated. Closed string sets that Rust models
//! as an enum but serialises through `as_str()` (severity, edge kind, snapshot
//! status, …) stay hand-written in `src/api-types.ts` and are pulled in by the
//! `#[ts(type = "...")]` overrides on the fields that carry them.

use std::fmt::Write as _;

use ts_rs::{Config, TS};

/// Union types that live in `src/api-types.ts` and may be referenced by the
/// generated declarations via `#[ts(type = "...")]`. Only the ones a
/// declaration actually mentions are imported, so the file does not trip
/// `no-unused-vars`.
const MANUAL_IMPORTS: &[&str] = &[
    "DiagramExportType",
    "EdgeKind",
    "ExportKind",
    "KindClass",
    "QueryKind",
    "Severity",
    "SnapshotStatus",
    "TopologyLevel",
    "TopologyNodeKind",
    "TopologyZone",
];

/// Push one type's declaration, exported.
fn decl<T: TS>(out: &mut String, cfg: &Config) {
    let _ = writeln!(out, "export {}\n", T::decl(cfg));
}

/// The full contents of `desktop/src/generated.ts`.
pub fn generated_typescript() -> String {
    // serde_json emits plain JSON numbers, so u64 must map to `number`, not the
    // `bigint` ts-rs defaults to — nothing on the wire is ever a BigInt.
    let cfg = Config::default().with_large_int("number");
    let mut out = String::new();

    // Ordered by hand rather than alphabetically so related types read together
    // and the diff stays small when one is edited.
    use crate::dto::*;
    use crate::topology::*;

    decl::<AppBootstrap>(&mut out, &cfg);
    decl::<SnapshotSummary>(&mut out, &cfg);
    decl::<SnapshotComparison>(&mut out, &cfg);
    decl::<EstateSnapshot>(&mut out, &cfg);
    decl::<TotalsDto>(&mut out, &cfg);
    decl::<TagCoverageDto>(&mut out, &cfg);
    decl::<SeverityCountsDto>(&mut out, &cfg);
    decl::<AzureMetadataDto>(&mut out, &cfg);
    decl::<SubscriptionDto>(&mut out, &cfg);
    decl::<ResourceGroupDto>(&mut out, &cfg);
    decl::<ResourceGroupSummaryDto>(&mut out, &cfg);
    decl::<ResourceDto>(&mut out, &cfg);
    decl::<ResourceTypeDto>(&mut out, &cfg);
    decl::<NameCountDto>(&mut out, &cfg);
    decl::<FindingDto>(&mut out, &cfg);
    decl::<EdgeDto>(&mut out, &cfg);
    decl::<QueryRunDto>(&mut out, &cfg);
    decl::<QueryDefDto>(&mut out, &cfg);
    decl::<QueryRowsDto>(&mut out, &cfg);

    decl::<TopologyRequest>(&mut out, &cfg);
    decl::<TopologyMode>(&mut out, &cfg);
    decl::<TopologyScope>(&mut out, &cfg);
    decl::<TopologyGraphDto>(&mut out, &cfg);
    decl::<LaneDto>(&mut out, &cfg);
    decl::<TopologyNodeDto>(&mut out, &cfg);
    decl::<TopologyLinkDto>(&mut out, &cfg);
    decl::<KindClassCountDto>(&mut out, &cfg);
    decl::<TopologyCountsDto>(&mut out, &cfg);

    decl::<CollectRequestDto>(&mut out, &cfg);
    decl::<CollectResultDto>(&mut out, &cfg);
    decl::<CollectionEvent>(&mut out, &cfg);
    decl::<ExportRequestDto>(&mut out, &cfg);
    decl::<ExportResultDto>(&mut out, &cfg);
    decl::<ExportEvent>(&mut out, &cfg);

    let used: Vec<&str> = MANUAL_IMPORTS
        .iter()
        .copied()
        .filter(|name| {
            // Word-boundary match so `KindClass` does not count as a use of
            // `KindClassCount`, and vice versa.
            out.split(|c: char| !c.is_alphanumeric() && c != '_')
                .any(|word| word == *name)
        })
        .collect();

    let mut header = String::from(
        "// @generated by `cargo test -p azdocs-desktop` — do not edit by hand.\n\
         //\n\
         // Source of truth: desktop/src-tauri/src/dto.rs and topology.rs.\n\
         // Regenerate with `cargo test -p azdocs-desktop`; CI fails if this file\n\
         // is stale. Hand-written unions live in ./api-types.\n\n",
    );
    if !used.is_empty() {
        let _ = writeln!(
            header,
            "import type {{\n{}\n}} from \"./api-types\";\n",
            used.iter()
                .map(|name| format!("  {name},"))
                .collect::<Vec<_>>()
                .join("\n")
        );
    }
    header.push_str(&out);
    header
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::generated_typescript;

    fn target() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/generated.ts")
    }

    /// Writing from a test (rather than build.rs) keeps codegen out of the
    /// normal build and makes staleness a CI diff rather than a silent rebuild.
    #[test]
    fn writes_the_typescript_bindings_when_run() {
        let contents = generated_typescript();
        std::fs::write(target(), &contents).expect("write desktop/src/generated.ts");
        assert!(
            contents.contains("export type Resource = "),
            "the DTO declarations should be present"
        );
    }

    #[test]
    fn keeps_hand_written_unions_on_the_fields_that_carry_them() {
        let contents = generated_typescript();
        for expected in [
            "kind: EdgeKind,",
            "severity: Severity,",
            "status: SnapshotStatus,",
            "kind: TopologyNodeKind,",
            "kindClass: KindClass,",
            "exportKind: ExportKind,",
        ] {
            assert!(
                contents.contains(expected),
                "generated bindings lost the `{expected}` union override"
            );
        }
    }
}
