mod common;

use std::io::Read;

use azdocs::config::BrandingConfig;
use azdocs::report::branding::BrandingContext;
use azdocs::report::{ReportContext, docx};
use azdocs::store::Store;

fn seeded_report() -> ReportContext {
    let store = Store::open_in_memory().unwrap();
    let id = common::seed_estate(&store);
    ReportContext::build(&store, &id).unwrap()
}

fn archive_entry(bytes: &[u8], name: &str) -> String {
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
    let mut entry = archive.by_name(name).unwrap();
    let mut content = String::new();
    entry.read_to_string(&mut content).unwrap();
    content
}

#[test]
fn docx_document_contains_headings_findings_and_severity_shading() {
    let report = seeded_report();
    let branding = BrandingContext::default();

    let bytes = docx::render(&report, &branding).unwrap();

    let document = archive_entry(&bytes, "word/document.xml");
    assert!(document.contains("Azure Estate Report"), "cover title");
    assert!(document.contains("Executive Summary"), "summary heading");
    assert!(document.contains("Findings"), "findings heading");
    assert!(
        document.contains("stprodapp01 allows public blob access"),
        "findings row"
    );
    // High-severity shading fill (same palette as the XLSX emitter).
    assert!(document.contains("F8CECC"), "severity cell shading");
}

#[test]
fn docx_footer_carries_branding_text() {
    let report = seeded_report();
    let branding = BrandingContext::default();

    let bytes = docx::render(&report, &branding).unwrap();

    let footer = archive_entry(&bytes, "word/footer1.xml");
    assert!(footer.contains("Generated by azdocs."), "footer: {footer}");
}

#[test]
fn docx_styles_carry_custom_primary_color() {
    let report = seeded_report();
    let config = BrandingConfig {
        primary_color: "#112233".to_owned(),
        company: "Contoso Ltd".to_owned(),
        ..BrandingConfig::default()
    };
    let branding = BrandingContext::resolve(&config, None).unwrap();

    let bytes = docx::render(&report, &branding).unwrap();

    let styles = archive_entry(&bytes, "word/styles.xml");
    assert!(styles.contains("112233"), "heading style color");
    let document = archive_entry(&bytes, "word/document.xml");
    assert!(document.contains("Contoso Ltd"), "company on cover");
}
