mod common;

use std::io::Read;

use azdocs::config::BrandingConfig;
use azdocs::diagram::DiagramScope;
use azdocs::diagram::assets::{self, DiagramAsset};
use azdocs::report::branding::BrandingContext;
use azdocs::report::{ReportContext, docx};
use azdocs::store::Store;

fn seeded() -> (ReportContext, Vec<DiagramAsset>) {
    let store = Store::open_in_memory().unwrap();
    let id = common::seed_estate(&store);
    let report = ReportContext::build(&store, &id).unwrap();
    let mut diagrams = assets::build_overviews(&store, &id, &DiagramScope::default()).unwrap();
    diagrams.extend(assets::build_resource_diagrams(&store, &id).unwrap());
    (report, diagrams)
}

fn themed(theme: &str) -> BrandingContext {
    BrandingContext::resolve(
        &BrandingConfig {
            theme: theme.to_owned(),
            ..BrandingConfig::default()
        },
        None,
    )
    .unwrap()
}

fn archive_entry(bytes: &[u8], name: &str) -> String {
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
    let mut entry = archive.by_name(name).unwrap();
    let mut content = String::new();
    entry.read_to_string(&mut content).unwrap();
    content
}

#[test]
fn docx_document_contains_headings_findings_and_severity_shading() {
    let (report, diagrams) = seeded();

    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();

    let document = archive_entry(&bytes, "word/document.xml");
    assert!(document.contains("Azure Estate Report"), "cover title");
    assert!(document.contains("Executive Summary"), "summary heading");
    assert!(document.contains("Findings"), "findings heading");
    assert!(
        document.contains("stprodapp01 allows public blob access"),
        "findings row"
    );
    // High-severity fill from the default theme's palette.
    assert!(document.contains("f8cecc"), "severity cell shading");
}

#[test]
fn docx_footer_carries_branding_text_and_a_page_count() {
    let (report, diagrams) = seeded();

    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();

    let footer = archive_entry(&bytes, "word/footer1.xml");
    assert!(footer.contains("Generated by azdocs."), "footer: {footer}");
    assert!(footer.contains("PAGE"), "page field");
    assert!(footer.contains("NUMPAGES"), "page-count field");
}

#[test]
fn docx_styles_carry_custom_primary_color() {
    let (report, diagrams) = seeded();
    let config = BrandingConfig {
        primary_color: "#112233".to_owned(),
        company: "Contoso Ltd".to_owned(),
        ..BrandingConfig::default()
    };
    let branding = BrandingContext::resolve(&config, None).unwrap();

    let bytes = docx::render(&report, &branding, &diagrams).unwrap();

    let styles = archive_entry(&bytes, "word/styles.xml");
    assert!(styles.contains("112233"), "heading style color");
    let document = archive_entry(&bytes, "word/document.xml");
    assert!(document.contains("Contoso Ltd"), "company on cover");
}

/// The original defect this rebuild fixed: no fonts, no page geometry and no
/// table sizing, which left Word rendering Times New Roman in tables that ran
/// off the page.
#[test]
fn docx_sets_fonts_page_geometry_and_fixed_table_widths() {
    let (report, diagrams) = seeded();

    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();

    let styles = archive_entry(&bytes, "word/styles.xml");
    assert!(
        styles.contains(r#"<w:rFonts w:ascii="Calibri""#),
        "document default font must be set, or Word falls back to Times New Roman"
    );
    assert!(styles.contains("w:outlineLvl"), "heading outline levels");

    let document = archive_entry(&bytes, "word/document.xml");
    assert!(document.contains(r#"<w:pgSz w:w="11906""#), "A4 page size");
    assert!(document.contains("<w:pgMar"), "page margins");
    assert!(document.contains("<w:titlePg />"), "bare cover page");
    assert!(
        document.contains(r#"<w:tblLayout w:type="fixed" />"#),
        "fixed table layout"
    );
    assert!(document.contains("<w:tblGrid>"), "explicit column grid");
    assert!(
        document.contains('\u{200B}'),
        "long ARM ids need zero-width break opportunities to wrap"
    );
}

#[test]
fn docx_embeds_resource_icons_and_diagrams() {
    let (report, diagrams) = seeded();

    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();

    let document = archive_entry(&bytes, "word/document.xml");
    assert!(document.contains("<w:drawing>"), "embedded images");
    assert!(document.contains("Relationships"), "per-resource diagram");
    assert!(document.contains("Settings"), "per-resource settings table");
    assert!(
        document.contains("Host Pool Type"),
        "flattened resource property"
    );

    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(&bytes)).unwrap();
    let images = (0..archive.len())
        .filter(|i| {
            archive
                .by_index(*i)
                .unwrap()
                .name()
                .starts_with("word/media/")
        })
        .count();
    assert!(images > 2, "expected type icons and diagrams, got {images}");
}

/// Word sits an inline image on the text baseline, so the type icon has to be
/// vertically centred by its cell instead — without costing the heading the
/// style the TOC field looks for.
#[test]
fn docx_type_heading_centres_its_icon_and_keeps_the_heading_style() {
    let (report, diagrams) = seeded();

    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();

    let document = archive_entry(&bytes, "word/document.xml");
    let heading_table = document
        .match_indices("<w:tbl>")
        .filter_map(|(start, _)| {
            let end = document[start..].find("</w:tbl>")? + start;
            let table = &document[start..end];
            (table.contains("<w:drawing>") && table.contains(r#"w:pStyle w:val="Heading1""#))
                .then_some(table)
        })
        .next()
        .expect("a resource-type heading pairing an icon with a Heading1 paragraph");

    assert_eq!(
        heading_table
            .matches(r#"<w:vAlign w:val="center" />"#)
            .count(),
        2,
        "both the icon and the heading cell must be vertically centred"
    );
    assert!(
        heading_table.contains(r#"<w:left w:w="0""#),
        "no left inset, so the icon lines up with the page text margin"
    );
    assert!(
        document.contains("TOC"),
        "the TOC field still has to be present alongside table-hosted headings"
    );
}

/// The layout strategy a theme chooses has to reach the output, or themes are
/// only a palette swap.
#[test]
fn docx_table_headers_differ_between_solid_and_hairline_themes() {
    let (report, diagrams) = seeded();

    let solid = docx::render(&report, &themed("fluent"), &diagrams).unwrap();
    let hairline = docx::render(&report, &themed("editorial"), &diagrams).unwrap();

    let solid_doc = archive_entry(&solid, "word/document.xml");
    let hairline_doc = archive_entry(&hairline, "word/document.xml");
    assert!(
        solid_doc.contains(r#"w:fill="0078d4""#),
        "fluent fills table headers with the primary colour"
    );
    assert!(
        !hairline_doc.contains(r#"w:fill="0078d4""#),
        "editorial leaves table headers unfilled"
    );
}

#[test]
fn docx_renders_every_shipped_theme() {
    let (report, diagrams) = seeded();

    for theme in azdocs::report::theme::ThemePack::builtin().unwrap().names() {
        let bytes = docx::render(&report, &themed(theme), &diagrams)
            .unwrap_or_else(|e| panic!("theme {theme} failed to render: {e}"));
        assert!(!bytes.is_empty(), "theme {theme} produced no bytes");
    }
}
