mod common;

use std::io::Read;

use azdocs::config::BrandingConfig;
use azdocs::diagram::assets::DiagramAsset;
use azdocs::report::branding::BrandingContext;
use azdocs::report::theme::{CoverStyle, TableStyle};
use azdocs::report::{ReportContext, docx};
use azdocs::store::Store;

fn seeded() -> (ReportContext, Vec<DiagramAsset>) {
    let store = Store::open_in_memory().unwrap();
    let id = common::seed_estate(&store);
    let report = ReportContext::build(&store, &id).unwrap();
    let diagrams = azdocs::diagram::assets::build_assessment(
        &report.analysis,
        &azdocs::labels::Labels::default(),
    );
    (report, diagrams)
}

#[test]
fn docx_reference_links_duplicate_names_by_id_and_resolves_every_bookmark() {
    let (mut report, _) = seeded();
    // Deliberately remove name uniqueness and vary the display ID casing.
    for section in &mut report.resource_types {
        for resource in &mut section.resources {
            resource.name = "same-name".into();
            resource.arm_id = resource.arm_id.to_uppercase();
        }
    }
    for resource in report.analysis.resources.values_mut() {
        resource.name = "same-name".into();
    }
    let bytes = docx::render_reference(&report, &BrandingContext::default(), &[]).unwrap();
    let xml = archive_entry(&bytes, "word/document.xml");
    let first_detail = xml.find("w:name=\"resource_").unwrap();
    let index = &xml[..first_detail];
    assert_eq!(
        index.matches("w:anchor=\"resource_").count(),
        report.analysis.resources.len()
    );
    for i in 0..report.analysis.resources.len() {
        assert!(index.contains(&format!("w:anchor=\"resource_{i}\"")));
        assert_eq!(xml.matches(&format!("w:name=\"resource_{i}\"")).count(), 1);
    }
    assert!(
        xml[first_detail..].contains("w:anchor=\"resource_"),
        "relationship and occurrence links"
    );
    for part in xml.split("w:anchor=\"").skip(1) {
        let target = part.split('"').next().unwrap();
        assert!(
            xml.contains(&format!("w:name=\"{target}\"")),
            "unresolved bookmark {target}"
        );
    }
}

fn themed(theme: &str) -> BrandingContext {
    BrandingContext::resolve(
        &BrandingConfig {
            theme: theme.to_owned(),
            ..BrandingConfig::default()
        },
        None,
    )
    .unwrap()
}

fn archive_entry(bytes: &[u8], name: &str) -> String {
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
    let mut entry = archive.by_name(name).unwrap();
    let mut content = String::new();
    entry.read_to_string(&mut content).unwrap();
    content
}

fn archive_contains_media(bytes: &[u8], expected: &[u8]) -> bool {
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
    (0..archive.len()).any(|index| {
        let mut entry = archive.by_index(index).unwrap();
        if !entry.name().starts_with("word/media/") {
            return false;
        }
        let mut content = Vec::new();
        entry.read_to_end(&mut content).unwrap();
        content == expected
    })
}

fn archive_contains_media_with_corner(bytes: &[u8], expected: [u8; 4]) -> bool {
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
    (0..archive.len()).any(|index| {
        let mut entry = archive.by_index(index).unwrap();
        if !entry.name().starts_with("word/media/") {
            return false;
        }
        let mut content = Vec::new();
        entry.read_to_end(&mut content).unwrap();
        image::load_from_memory(&content)
            .map(|image| image.to_rgba8().get_pixel(0, 0).0 == expected)
            .unwrap_or(false)
    })
}

#[test]
fn docx_document_contains_headings_findings_and_severity_shading() {
    let (report, diagrams) = seeded();
    let branding = BrandingContext::default();
    let high_fill = branding
        .tokens
        .palette
        .severity
        .high
        .fill
        .trim_start_matches('#');

    let bytes = docx::render(&report, &branding, &diagrams).unwrap();

    let document = archive_entry(&bytes, "word/document.xml");
    assert!(document.contains("Azure Estate Report"), "cover title");
    assert!(document.contains("Executive assessment"), "summary heading");
    assert!(
        document.contains("Audit findings and review priorities"),
        "findings heading"
    );
    assert!(
        document.contains("stprodapp01 allows public blob access"),
        "findings row"
    );
    // High-severity fill from the default theme's palette.
    assert!(document.contains(high_fill), "severity cell shading");
}

#[test]
fn docx_footer_carries_branding_text_and_a_page_count() {
    let (report, diagrams) = seeded();

    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();

    let footer = archive_entry(&bytes, "word/footer1.xml");
    assert!(footer.contains("Generated by azdocs."), "footer: {footer}");
    assert!(footer.contains("PAGE"), "page field");
    assert!(footer.contains("NUMPAGES"), "page-count field");
}

#[test]
fn docx_cover_embeds_the_matching_azdocs_product_mark() {
    let (report, diagrams) = seeded();
    let field_report = BrandingContext::default();
    let mut block_branding = field_report.clone();
    block_branding.tokens.layout.cover = CoverStyle::Block;

    let light = docx::render(&report, &field_report, &diagrams).unwrap();
    let dark = docx::render(&report, &block_branding, &diagrams).unwrap();

    let light_mark = azdocs::diagram::png::from_svg_transparent(
        include_str!("../docs/marks/assets/azdocs-mark-primary.svg"),
        0.25,
    )
    .unwrap();

    assert!(archive_contains_media(&light, &light_mark));
    assert!(
        archive_contains_media_with_corner(&dark, [0x1c, 0x24, 0x30, 0xff]),
        "the dark-cover mark needs a matte matching the cover rather than a transparent or white square"
    );
}

#[test]
fn docx_requests_a_field_refresh_for_toc_page_numbers() {
    let (report, diagrams) = seeded();

    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();

    let document = archive_entry(&bytes, "word/document.xml");
    let toc_instruction = document.find("<w:instrText>TOC").expect("TOC field code");
    let toc_prefix = &document[toc_instruction.saturating_sub(200)..toc_instruction];
    assert!(
        toc_prefix.contains(r#"w:fldCharType="begin" w:dirty="true""#),
        "the cached TOC must be marked stale"
    );
    assert!(document.contains("PAGEREF"), "TOC page-reference fields");
    assert!(
        !document.contains(r#"w:pos="80000""#),
        "contents page-number tabs must fit the printable column"
    );

    let settings = archive_entry(&bytes, "word/settings.xml");
    assert!(
        settings.contains(r#"<w:updateFields w:val="true" />"#),
        "Word must recalculate the TOC after it has laid out the document"
    );
}

#[test]
fn docx_reserves_custom_primary_color_for_brand_accents() {
    let (report, diagrams) = seeded();
    let config = BrandingConfig {
        primary_color: "#112233".to_owned(),
        company: "Contoso Ltd".to_owned(),
        ..BrandingConfig::default()
    };
    let branding = BrandingContext::resolve(&config, None).unwrap();
    assert_eq!(branding.tokens.palette.accent, "#112233");

    let bytes = docx::render(&report, &branding, &diagrams).unwrap();

    let styles = archive_entry(&bytes, "word/styles.xml");
    assert!(styles.contains("1c2430"), "headings use Field Report ink");
    assert!(
        !styles.contains("112233"),
        "brand colour is not document chrome"
    );
    let document = archive_entry(&bytes, "word/document.xml");
    assert!(document.contains("Contoso Ltd"), "company on cover");
}

/// The original defect this rebuild fixed: no fonts, no page geometry and no
/// table sizing, which left Word rendering Times New Roman in tables that ran
/// off the page.
#[test]
fn docx_sets_fonts_page_geometry_and_fixed_table_widths() {
    let (report, diagrams) = seeded();

    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();

    let styles = archive_entry(&bytes, "word/styles.xml");
    assert!(
        styles.contains(r#"<w:rFonts w:ascii="Arial""#),
        "document default font must be set, or Word falls back to Times New Roman"
    );
    assert!(
        styles.contains(r#"<w:rFonts w:ascii="Charter""#),
        "Field Report headings use the serif display face"
    );
    assert!(styles.contains("w:outlineLvl"), "heading outline levels");

    let document = archive_entry(&bytes, "word/document.xml");
    assert!(document.contains(r#"<w:pgSz w:w="11906""#), "A4 page size");
    assert!(document.contains("<w:pgMar"), "page margins");
    assert!(document.contains("<w:titlePg />"), "bare cover page");
    assert!(
        document.contains(r#"<w:tblLayout w:type="fixed" />"#),
        "fixed table layout"
    );
    assert!(document.contains("<w:tblGrid>"), "explicit column grid");
    assert!(
        document.contains('\u{200B}'),
        "long ARM ids need zero-width break opportunities to wrap"
    );
}

#[test]
fn docx_embeds_resource_icons_and_diagrams() {
    let (report, diagrams) = seeded();

    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();

    let document = archive_entry(&bytes, "word/document.xml");
    assert!(document.contains("<w:drawing>"), "embedded images");
    assert!(document.contains("Architecture and dependencies"));
    assert!(document.contains("Configuration comparisons"));
    assert!(!document.contains("Resources by type"));
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(&bytes)).unwrap();
    let images = (0..archive.len())
        .filter(|i| {
            archive
                .by_index(*i)
                .unwrap()
                .name()
                .starts_with("word/media/")
        })
        .count();
    assert!(images > 2, "expected type icons and diagrams, got {images}");
}

/// Word sits an inline image on the text baseline, so the type icon has to be
/// vertically centred by its cell instead — without costing the heading the
/// style the TOC field looks for.
#[test]
fn docx_type_heading_centres_its_icon_and_keeps_the_level_two_heading_style() {
    let (report, diagrams) = seeded();

    let bytes = docx::render_reference(&report, &BrandingContext::default(), &diagrams).unwrap();

    let document = archive_entry(&bytes, "word/document.xml");
    let heading_table = document
        .match_indices("<w:tbl>")
        .filter_map(|(start, _)| {
            let end = document[start..].find("</w:tbl>")? + start;
            let table = &document[start..end];
            (table.contains("<w:drawing>") && table.contains(r#"w:pStyle w:val="Heading2""#))
                .then_some(table)
        })
        .next()
        .expect("a resource-type heading pairing an icon with a Heading2 paragraph");

    assert_eq!(
        heading_table
            .matches(r#"<w:vAlign w:val="center" />"#)
            .count(),
        2,
        "both the icon and the heading cell must be vertically centred"
    );
    assert!(
        heading_table.contains(r#"<w:left w:w="0""#),
        "no left inset, so the icon lines up with the page text margin"
    );
    assert!(
        document.contains("TOC"),
        "the TOC field still has to be present alongside table-hosted headings"
    );
}

#[test]
fn docx_field_report_uses_plain_headings_and_a_running_header() {
    let (report, diagrams) = seeded();

    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();

    let document = archive_entry(&bytes, "word/document.xml");
    assert!(
        !document.contains("<w:numId w:val=\"42\""),
        "Field Report headings are names, not chapter numbers"
    );
    let header = archive_entry(&bytes, "word/header1.xml");
    assert!(header.contains("STYLEREF"), "running chapter field");
    assert!(
        header.contains("Heading 1"),
        "running header follows Heading 1"
    );
    assert!(
        header.contains("Azure Estate Report"),
        "document title at right"
    );
}

#[test]
fn docx_keeps_headings_figures_and_subheadings_with_their_content() {
    let (report, diagrams) = seeded();
    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();
    let document = archive_entry(&bytes, "word/document.xml");
    for text in ["Architecture and dependencies", "What was observed"] {
        let at = document.rfind(text).unwrap();
        let start = document[..at].rfind("<w:p ").unwrap();
        assert!(document[start..at].contains("<w:keepNext />"));
    }
    assert!(document.contains("w:bookmarkStart"));
    assert!(document.contains("w:anchor=\"issue_"));
}

#[test]
fn docx_reference_settings_use_smaller_bordered_tables_and_resource_icons() {
    let (report, diagrams) = seeded();

    let bytes = docx::render_reference(&report, &BrandingContext::default(), &diagrams).unwrap();

    let document = archive_entry(&bytes, "word/document.xml").replace('\u{200b}', "");
    let setting = document
        .rfind("Public blob access")
        .expect("stored storage setting");
    let table_start = document[..setting]
        .rfind("<w:tbl>")
        .expect("setting table start");
    let table_end = setting
        + document[setting..]
            .find("</w:tbl>")
            .expect("setting table end");
    let table = &document[table_start..table_end];
    assert!(
        table.contains("<w:insideV w:val=\"single\""),
        "vertical cell borders"
    );
    assert!(
        table.contains("<w:insideH w:val=\"single\""),
        "horizontal cell borders"
    );
    assert!(
        table.contains("<w:sz w:val=\"18\""),
        "9 point reference table text"
    );
    let name = document.rfind("stprodapp01").unwrap();
    // Find the resource plate itself, which includes its icon in the same paragraph.
    assert!(
        document[..name]
            .split("</w:p>")
            .any(|p| p.contains("<w:drawing>") && p.contains("stprodapp01"))
    );
}

#[test]
fn docx_evidence_examples_use_native_bullets() {
    let (report, diagrams) = seeded();
    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();
    let document = archive_entry(&bytes, "word/document.xml");
    assert!(document.contains("<w:numId w:val=\"43\""));
    let numbering = archive_entry(&bytes, "word/numbering.xml");
    assert!(numbering.contains("w:val=\"bullet\""));
}

#[test]
fn docx_divider_page_strategy_keeps_real_chapter_headings() {
    let (report, diagrams) = seeded();
    let mut branding = BrandingContext::default();
    branding.tokens.layout.divider_pages = true;

    let bytes = docx::render(&report, &branding, &diagrams).unwrap();

    let document = archive_entry(&bytes, "word/document.xml");
    assert!(
        document.contains(r#"<w:trHeight w:val="14450" w:hRule="exact" />"#),
        "divider occupies the printable page while reserving its trailing paragraph"
    );
    assert!(
        document.matches(r#"w:pStyle w:val="Heading1""#).count() > 4,
        "each divider keeps a real Heading 1 for navigation"
    );
}

#[test]
fn docx_implements_band_editorial_and_printable_block_covers() {
    let (report, diagrams) = seeded();
    let editorial_branding = BrandingContext::default();
    let mut band_branding = editorial_branding.clone();
    band_branding.tokens.layout.cover = CoverStyle::Band;
    band_branding.tokens.layout.cover_band_pt = 96.0;
    let mut block_branding = editorial_branding.clone();
    block_branding.tokens.layout.cover = CoverStyle::Block;

    let band = docx::render(&report, &band_branding, &diagrams).unwrap();
    let editorial = docx::render(&report, &editorial_branding, &diagrams).unwrap();
    let block = docx::render(&report, &block_branding, &diagrams).unwrap();

    let band_document = archive_entry(&band, "word/document.xml");
    let editorial_document = archive_entry(&editorial, "word/document.xml");
    let block_document = archive_entry(&block, "word/document.xml");
    assert!(band_document.contains(r#"w:val="1920" w:hRule="exact""#));
    assert!(!editorial_document.contains(r#"w:val="1920" w:hRule="exact""#));
    assert!(
        block_document.contains(r#"w:val="14450" w:hRule="exact""#),
        "block cover fills the printable area without spilling its trailing paragraph"
    );
}

#[test]
fn docx_comparison_headers_repeat_and_heading_weights_are_regular() {
    let (report, diagrams) = seeded();
    let bytes = docx::render(&report, &BrandingContext::default(), &diagrams).unwrap();
    let document = archive_entry(&bytes, "word/document.xml");
    for row in document.split("<w:tr>").skip(1) {
        let row = row.split("</w:tr>").next().unwrap();
        if row.contains("AzdocsTableHeader") {
            assert!(row.contains("<w:tblHeader/>"));
        }
    }
    let styles = archive_entry(&bytes, "word/styles.xml");
    for level in 1..=3 {
        let at = styles
            .find(&format!("w:styleId=\"Heading{level}\""))
            .unwrap();
        let style = styles[at..].split("</w:style>").next().unwrap();
        assert!(!style.contains("<w:b />"));
    }
}

/// User-authored themes can still choose another table strategy, so the closed
/// strategy set remains covered even though only one built-in theme ships.
#[test]
fn docx_table_headers_differ_between_solid_and_hairline_strategies() {
    let (report, diagrams) = seeded();
    let hairline_branding = BrandingContext::default();
    let mut solid_branding = hairline_branding.clone();
    solid_branding.tokens.layout.table = TableStyle::SolidHeader;
    let primary = solid_branding
        .tokens
        .palette
        .primary
        .trim_start_matches('#')
        .to_owned();

    let solid = docx::render(&report, &solid_branding, &diagrams).unwrap();
    let hairline = docx::render(&report, &hairline_branding, &diagrams).unwrap();

    let solid_doc = archive_entry(&solid, "word/document.xml");
    let hairline_doc = archive_entry(&hairline, "word/document.xml");
    assert!(
        solid_doc.contains(&format!(r#"w:fill="{primary}""#)),
        "solid headers use the primary colour"
    );
    assert!(
        !hairline_doc.contains(&format!(r#"w:fill="{primary}""#)),
        "hairline headers remain unfilled"
    );
}

#[test]
fn docx_renders_every_shipped_theme() {
    let (report, diagrams) = seeded();

    for theme in azdocs::report::theme::ThemePack::builtin().unwrap().names() {
        let bytes = docx::render(&report, &themed(theme), &diagrams)
            .unwrap_or_else(|e| panic!("theme {theme} failed to render: {e}"));
        assert!(!bytes.is_empty(), "theme {theme} produced no bytes");
    }
}
