// @generated by `cargo test -p azdocs-desktop` — do not edit by hand.
//
// Source of truth: desktop/src-tauri/src/dto.rs and topology.rs.
// Regenerate with `cargo test -p azdocs-desktop`; CI fails if this file
// is stale. Hand-written unions live in ./api-types; the labels type
// is inferred from generated-labels.json in ./labels.

import type {
  EdgeKind,
  ExportKind,
  KindClass,
  QueryKind,
  Severity,
  SnapshotStatus,
  TopologyLevel,
  TopologyNodeKind,
  TopologyZone,
} from "./api-types";

import type {
  Labels,
} from "./labels";

export type Cloud = "public" | "usgov" | "china";

export type SettingsValues = { schema_version: number, default_tenant?: string | null,
/**
 * Shared cloud default; `TenantProfile.cloud` overrides it.
 */
cloud: Cloud, tenants: { [key in string]: TenantProfile }, collect: CollectConfig, audit: AuditConfig, storage: StorageConfig, branding: BrandingConfig, };

export type TenantProfile = { name: string, tenant_id: string, client_id: string,
/**
 * Overrides the shared `cloud` for this tenant.
 */
cloud?: Cloud | null, secret_ref?: string | null, secret_env?: string | null, collect: CollectOverrides, audit: AuditOverrides, branding: BrandingOverrides, };

export type CollectOverrides = { subscriptions?: Array<string> | null, concurrency?: number | null, retry?: RetryConfig | null, };

export type AuditOverrides = { required_tags?: Array<string> | null, };

export type BrandingOverrides = { company?: string | null, title?: string | null, subtitle?: string | null, primary_color?: string | null, accent_color?: string | null, logo?: string | null, page_size?: string | null, margin?: string | null, footer?: string | null, theme?: string | null, labels?: string | null, font_family?: string | null, mono_family?: string | null, font_dir?: string | null, };

export type CollectConfig = {
/**
 * Subscription ids to collect; empty means all visible to the credential.
 */
subscriptions: Array<string>, concurrency: number, retry: RetryConfig, };

export type RetryConfig = {
/**
 * Attempts per request, 1–10.
 */
max_attempts: number,
/**
 * First backoff wait in milliseconds; doubles per attempt.
 */
base_delay_ms: number,
/**
 * Longest single wait in seconds, including a server's Retry-After.
 */
max_delay_secs: number,
/**
 * Whole-request timeout in seconds.
 */
timeout_secs: number,
/**
 * TCP/TLS connect timeout in seconds.
 */
connect_timeout_secs: number, };

export type AuditConfig = { required_tags: Array<string>, };

export type StorageConfig = { db_path: string, };

export type BrandingConfig = {
/**
 * Organisation name shown on covers and footers; empty hides it.
 */
company: string,
/**
 * Report title (cover page, HTML `<h1>`).
 */
title: string,
/**
 * Optional subtitle under the title; empty hides it.
 */
subtitle: string,
/**
 * Main brand color as `#rrggbb` (headings, links, badges).
 */
primary_color: string,
/**
 * Secondary color as `#rrggbb` (dark-mode links, rules, highlights).
 */
accent_color: string,
/**
 * Path to a logo image (.png/.jpg/.jpeg/.gif/.svg), relative paths are
 * resolved against the config file's directory.
 */
logo: string | null,
/**
 * PDF paper size (a Typst paper name, e.g. "a4" or "us-letter").
 */
page_size: string,
/**
 * PDF page margin (a Typst length, e.g. "2cm" or "1in").
 */
margin: string,
/**
 * Footer text on every report page.
 */
footer: string,
/**
 * Document theme: a file stem from `data/themes/` or from
 * `<config dir>/azdocs/themes/`. An unknown name lists the valid ones.
 */
theme: string,
/**
 * Wording set: a file stem from `data/labels/` or from
 * `<config dir>/azdocs/labels/`. An unknown name lists the valid ones.
 */
labels: string,
/**
 * Overrides the theme's `typography.sans` for the PDF and HTML; the
 * family must be vendored or supplied via `font_dir`. Empty keeps it.
 */
font_family: string,
/**
 * Overrides the theme's `typography.mono`; empty keeps it.
 */
mono_family: string,
/**
 * Directory of extra `.ttf`/`.otf` faces loaded into the PDF font book,
 * so a corporate typeface can be used without vendoring it. Relative
 * paths resolve against this config file's directory.
 */
font_dir: string | null, };

export type TenantSummary = { reference: string, name: string, tenantId: string, configured: boolean, };

export type SettingsDocumentDto = { path: string, revision: string, values?: SettingsValues | null, legacy: boolean, legacyTenantId?: string | null, legacyClientId?: string | null, error?: string | null, check?: ConnectionCheck | null, };

export type SettingsSaveRequest = { revision: string, values: SettingsValues, newSecrets: { [key in string]: string }, secretTokens: { [key in string]: string }, };

export type SettingsTestResult = { check: ConnectionCheck, secretToken?: string | null, };

export type SettingsTestRequest = { reference: string, values: SettingsValues, newSecret: string | null, secretToken: string | null, };

export type ConnectionCheck = { checkedAt: string, subscriptions: Array<VisibleSubscription>, inaccessibleSubscriptions: Array<string>, verdict: PermissionVerdict, grants: Array<PermissionGrant>, issues: Array<AccessIssue>, };

export type VisibleSubscription = { id: string, name: string, };

export type PermissionGrant = { scope: string, role: string, roleId: string, verdict: PermissionVerdict, actions: Array<string>, };

export type PermissionVerdict = "read_only" | "broader_grants" | "unable_to_verify";

export type AccessIssue = { kind: AccessIssueKind, scope: string, };

export type AccessIssueKind = "identity_unavailable" | "no_subscriptions" | "assignment_read_failed" | "definition_read_failed" | "conditional_grant" | "unsupported_permissions" | "no_assignments" | "inaccessible_subscription";

export type AppBootstrap = { tenants: Array<TenantSummary>, activeTenantId?: string | null, configError?: string | null, databasePath: string, configPath: string, configFound: boolean, hasCredentials: boolean, requiredTags: Array<string>, snapshots: Array<SnapshotSummary>, latestSnapshotId?: string | null,
/**
 * Every word the frontend shows, already resolved against the user's
 * overrides. Typed in TypeScript from `generated-labels.json`.
 */
labels: Labels, };

export type SnapshotSummary = { id: string, createdAt: string, tenantId: string, status: SnapshotStatus, notes?: string | null, subscriptions: number, resources: number, findings: number, };

export type SnapshotComparison = { baseSnapshotId: string, targetSnapshotId: string, added: Array<string>, removed: Array<string>, changed: Array<string>,
/**
 * Field changes per changed resource id.
 */
fields: { [key in string]: Array<FieldChange> }, findingsAdded: Array<FindingRef>, findingsResolved: Array<FindingRef>, edgesAdded: Array<EdgeRef>, edgesRemoved: Array<EdgeRef>, subscriptionsAdded: Array<string>, subscriptionsRemoved: Array<string>, resourceGroupsAdded: Array<string>, resourceGroupsRemoved: Array<string>, baseCounts: ComparisonCounts, targetCounts: ComparisonCounts, };

export type FieldChange = {
/**
 * Which stored column: `name`, `tags`, `properties`, ...
 */
field: string,
/**
 * Dotted path inside the column; empty for scalar columns.
 */
path: string, before: unknown, after: unknown, };

export type FindingRef = { queryName: string, category: string, severity: Severity, resourceId?: string | null, title: string, };

export type EdgeRef = { sourceId: string, targetId: string, kind: EdgeKind, };

export type ComparisonCounts = { resources: number, findings: number, high: number, medium: number, low: number, info: number, edges: number, subscriptions: number, resourceGroups: number, };

export type TrendPoint = { snapshotId: string, createdAt: string, status: SnapshotStatus, subscriptions: number, resources: number, tagged: number, findings: number, high: number, medium: number, low: number, info: number, edges: number, };

export type EstateSnapshot = { id: string, createdAt: string, tenantId: string, status: SnapshotStatus, notes?: string | null, totals: Totals, tagCoverage: TagCoverage, severityCounts: SeverityCounts, azureMetadata: AzureMetadata, governance: Governance, subscriptions: Array<Subscription>, resourceGroups: Array<ResourceGroup>,
/**
 * Every group the relationship map can open, synthetic ones included.
 */
resourceGroupSummaries: Array<ResourceGroupSummary>, resources: Array<Resource>, resourceTypes: Array<ResourceType>, locations: Array<NameCount>, findings: Array<Finding>, edges: Array<Edge>, queryRuns: Array<QueryRun>,
/**
 * Already interpreted and labelled in Rust; the frontend only renders cells.
 */
evidenceSummaries: Array<EvidenceTable>,
/**
 * The usable snapshot this one is compared against; None for the earliest.
 */
previousSnapshotId?: string | null, previousDiff?: SnapshotComparison | null,
/**
 * Usable snapshots of this tenant up to this one, oldest first.
 */
trend: Array<TrendPoint>, };

export type Totals = { subscriptions: number, resourceGroups: number, resources: number, findings: number, };

export type TagCoverage = { tagged: number, untagged: number, percent: number, };

export type SeverityCounts = { high: number, medium: number, low: number, info: number, };

export type AzureMetadata = { locations: { [key in string]: string }, kinds: { [key in string]: string }, };

export type Governance = {
/**
 * How many distinct tag keys the estate uses.
 */
distinctKeys: number,
/**
 * The most-used keys, busiest first.
 */
topKeys: Array<TagKeyCoverage>,
/**
 * Coverage per subscription that holds resources, by name.
 */
subscriptions: Array<SubscriptionCoverage>,
/**
 * Resources missing at least one required tag.
 */
nonCompliant: number,
/**
 * The groups holding most of them, worst first.
 */
worstGroups: Array<GroupCompliance>, };

export type TagKeyCoverage = { key: string, count: number,
/**
 * Share of the *tagged* resources carrying this key.
 */
percent: number, };

export type SubscriptionCoverage = { subscriptionId: string, displayName: string, percent: number,
/**
 * Already judged against the healthy-coverage threshold.
 */
healthy: boolean, };

export type GroupCompliance = { name: string, subscriptionName: string,
/**
 * Every resource in the group, not just the offenders.
 */
resources: number, nonCompliant: number,
/**
 * Which required tags were missed anywhere in the group, sorted.
 */
missedTags: Array<string>,
/**
 * Already judged against the flagged-share threshold.
 */
flagged: boolean, };

export type Subscription = { id: string, displayName: string, state?: string | null, tags?: Record<string, unknown>, };

export type ResourceGroup = { id: string, name: string, subscriptionId: string, location?: string | null, tags?: Record<string, unknown>, };

export type ResourceGroupSummary = { id: string, name: string, subscriptionId: string,
/**
 * Resolved here so the UI never has to join against the subscription list.
 */
subscriptionName: string, resourceCount: number, findingCount: number,
/**
 * Resource ids in this group, ordered by name then id.
 */
resourceIds: Array<string>, };

export type Resource = { id: string, displayId: string, name: string, azureType: string, kind?: string | null, location?: string | null, resourceGroup?: string | null, subscriptionId: string, tags?: Record<string, unknown>, sku?: unknown, identity?: unknown, properties?: Record<string, unknown>, findingCount: number, edgeCount: number, };

export type ResourceType = { azureType: string, displayName: string, count: number, icon: string, color: string, };

export type NameCount = { name: string, count: number, };

export type Finding = { queryName: string, category: string, severity: Severity, resourceId?: string | null, title: string, detail?: unknown, };

export type Edge = { sourceId: string, targetId: string, kind: EdgeKind, properties?: unknown, };

export type QueryRun = { provenance?: QueryProvenance | null, queryName: string, category: string, rowCount?: number | null, durationMs?: number | null, error?: string | null, };

export type QueryProvenance = { kql: string, kqlSha256: string, description: string, kind: string, authorizationScope: string, subscriptions: Array<string>, sourceUrls: Array<string>, reviewedOn?: string | null, revision?: string | null, };

export type EvidenceTable = { key: string, title: string, note: string, status: string, columns: Array<string>, rows: Array<Array<string>>, };

export type QueryDefMeta = { name: string, category: string, kind: QueryKind, description: string, };

export type QueryRows = { queryName: string, columns: Array<string>, rows: Array<Record<string, unknown>>, };

export type TopologyRequest = { snapshotId?: string | null, mode: TopologyMode, scope: TopologyScope, };

export type TopologyMode = { "kind": "estate",
/**
 * Subscription ids the user has expanded; empty means "auto".
 */
expandedSubscriptions: Array<string>, } | { "kind": "group", groupId: string, } | { "kind": "neighbourhood", resourceId: string, depth: number,
/**
 * Edge-kind classes to include; empty means all.
 */
kindClasses: Array<string>, };

export type TopologyScope = {
/**
 * Subscription ids to include; empty means all.
 */
subscriptions: Array<string>,
/**
 * Azure types to include; empty means all.
 */
azureTypes: Array<string>, showUnconnected: boolean, };

export type TopologyGraph = { level: TopologyLevel, lanes: Array<TopologyLane>, nodes: Array<TopologyNode>, links: Array<TopologyLink>, kindClasses: Array<KindClassCount>, counts: TopologyCounts, };

export type TopologyLane = { subscriptionId: string, name: string, expanded: boolean, groupCount: number, resourceCount: number, findingCount: number, };

export type TopologyNode = { id: string,
/**
 * resource | resource-group | subscription | vnet | subnet | aggregate
 */
kind: TopologyNodeKind, name: string, subtitle: string, azureType?: string | null,
/**
 * Subscription id this node belongs to (estate mode lanes).
 */
lane?: string | null,
/**
 * Containment: a subnet's vnet, a placed resource's subnet.
 */
parentId?: string | null,
/**
 * core | unconnected — which shelf the group view lays the node in.
 */
zone?: TopologyZone,
/**
 * BFS distance from the subject in neighbourhood mode.
 */
hop?: number | null,
/**
 * Members folded or aggregated into this node (resource ids).
 */
memberIds: Array<string>, count: number, findingCount: number, resourceId?: string | null, groupId?: string | null,
/**
 * Resource groups rolled into an estate-level "unconnected groups" tile.
 * Empty on every other node; `member_ids` still lists their resources.
 */
groupIds: Array<string>, };

export type TopologyLink = { sourceId: string, targetId: string, label: string, kindClass: KindClass, count: number, };

export type KindClassCount = { class: string, count: number, };

export type TopologyCounts = {
/**
 * Resources (or groups, at estate level) in scope.
 */
total: number,
/**
 * Drawn as their own node.
 */
drawn: number,
/**
 * Folded into a host node (NIC into VM, child into parent).
 */
folded: number,
/**
 * Rolled into ×N aggregate tiles or collapsed lanes.
 */
aggregated: number,
/**
 * Neighbours in other groups drawn as ghost stubs (group view only).
 */
external: number,
/**
 * Excluded by the request's filters (never silently — always counted).
 */
hiddenByFilter: number, totalLinks: number, drawnLinks: number, };

export type CollectRequest = { subscriptions: Array<string>, notes?: string | null, };

export type CollectResult = { snapshotId: string, status: string, queriesRun: number, queriesFailed: number, rowsIngested: number, screenshots?: WebsiteBatchResult | null, };

export type CollectionStage = "inventory" | "discovery" | "capture";

export type CollectionQueryProgress = { completed: number, total: number, rows: number, failed: number, latestQuery?: string | null, };

export type CollectionEvent = { "event": "permissions", "data": { check: ConnectionCheck, } } | { "event": "stage", "data": { stage: CollectionStage, } } | { "event": "queries", "data": { progress: CollectionQueryProgress, } } | { "event": "phase", "data": { message: string, } } | { "event": "complete", "data": { snapshotId: string, } } | { "event": "cancelled", "data": { snapshotId: string, } } | { "event": "failed", "data": { message: string, } } | { "event": "screenshots", "data": { progress: WebsiteProgress, } };

export type WebsiteState = { endpoints: Array<WebsiteEndpoint>, captures: Array<WebsiteCapture>, evidenceErrors: Array<string>, };

export type WebsiteEndpoint = { resourceId: string, resourceName: string, source: string, hostname?: string | null, url?: string | null, status: 'ready' | 'disabled' | 'wildcard' | 'missing_hostname' | 'invalid_hostname' | 'missing_evidence', };

export type WebsiteCapture = { url: string, finalUrl?: string | null, capturedAt?: string | null, attemptedAt: string, status: 'running' | 'captured' | 'failed' | 'cancelled' | 'interrupted', error?: string | null, renderer?: string | null, width?: number | null, height?: number | null, };

export type WebsiteCaptureRequest = { snapshotId: string, urls: Array<string>, retryOnly: boolean, };

export type WebsiteProgress = { completed: number, total: number, url?: string | null, captured: number, failed: number, cancelled: boolean, };

export type WebsiteBatchResult = { captured: number, failed: number, skipped: number, cancelled: boolean, error?: string | null, };

export type ExportRequest = { includeReference?: boolean | null, snapshotId: string, destination: string, exportKind: ExportKind, formats: Array<string>, diagramType?: string | null, subscriptionId?: string | null, resourceGroup?: string | null, };

export type ExportResult = { destination: string, outputs: Array<string>,
/**
 * True when the run was stopped on request; `outputs` lists what was
 * written before that.
 */
cancelled: boolean, };

export type ExportEvent = { "event": "phase", "data": { message: string, } } | { "event": "complete", "data": { outputCount: number, } } | { "event": "cancelled", "data": { outputCount: number, } } | { "event": "failed", "data": { message: string, } };

