// @generated by `cargo test -p azdocs-desktop` — do not edit by hand.
//
// Source of truth: desktop/src-tauri/src/dto.rs and topology.rs.
// Regenerate with `cargo test -p azdocs-desktop`; CI fails if this file
// is stale. Hand-written unions live in ./api-types; the labels type
// is inferred from generated-labels.json in ./labels.

import type {
  EdgeKind,
  ExportKind,
  KindClass,
  QueryKind,
  Severity,
  SnapshotStatus,
  TopologyLevel,
  TopologyNodeKind,
  TopologyZone,
} from "./api-types";

import type {
  Labels,
} from "./labels";

export type AppBootstrap = { databasePath: string, configPath: string, configFound: boolean, hasCredentials: boolean, requiredTags: Array<string>, snapshots: Array<SnapshotSummary>, latestSnapshotId?: string | null, 
/**
 * Every word the frontend shows, already resolved against the user's
 * overrides. Typed in TypeScript from `generated-labels.json`.
 */
labels: Labels, };

export type SnapshotSummary = { id: string, createdAt: string, tenantId: string, status: SnapshotStatus, notes?: string | null, subscriptions: number, resources: number, findings: number, };

export type SnapshotComparison = { baseSnapshotId: string, targetSnapshotId: string, added: Array<string>, removed: Array<string>, changed: Array<string>, };

export type EstateSnapshot = { id: string, createdAt: string, tenantId: string, status: SnapshotStatus, notes?: string | null, totals: Totals, tagCoverage: TagCoverage, severityCounts: SeverityCounts, azureMetadata: AzureMetadata, governance: Governance, subscriptions: Array<Subscription>, resourceGroups: Array<ResourceGroup>, 
/**
 * Every group the relationship map can open, synthetic ones included.
 */
resourceGroupSummaries: Array<ResourceGroupSummary>, resources: Array<Resource>, resourceTypes: Array<ResourceType>, locations: Array<NameCount>, findings: Array<Finding>, edges: Array<Edge>, queryRuns: Array<QueryRun>, previousDiff?: SnapshotComparison | null, };

export type Totals = { subscriptions: number, resourceGroups: number, resources: number, findings: number, };

export type TagCoverage = { tagged: number, untagged: number, percent: number, };

export type SeverityCounts = { high: number, medium: number, low: number, info: number, };

export type AzureMetadata = { locations: { [key in string]: string }, kinds: { [key in string]: string }, };

export type Governance = { 
/**
 * How many distinct tag keys the estate uses.
 */
distinctKeys: number, 
/**
 * The most-used keys, busiest first.
 */
topKeys: Array<TagKeyCoverage>, 
/**
 * Coverage per subscription that holds resources, by name.
 */
subscriptions: Array<SubscriptionCoverage>, 
/**
 * Resources missing at least one required tag.
 */
nonCompliant: number, 
/**
 * The groups holding most of them, worst first.
 */
worstGroups: Array<GroupCompliance>, };

export type TagKeyCoverage = { key: string, count: number, 
/**
 * Share of the *tagged* resources carrying this key.
 */
percent: number, };

export type SubscriptionCoverage = { subscriptionId: string, displayName: string, percent: number, 
/**
 * Already judged against the healthy-coverage threshold.
 */
healthy: boolean, };

export type GroupCompliance = { name: string, subscriptionName: string, 
/**
 * Every resource in the group, not just the offenders.
 */
resources: number, nonCompliant: number, 
/**
 * Which required tags were missed anywhere in the group, sorted.
 */
missedTags: Array<string>, 
/**
 * Already judged against the flagged-share threshold.
 */
flagged: boolean, };

export type Subscription = { id: string, displayName: string, state?: string | null, tags?: Record<string, unknown>, };

export type ResourceGroup = { id: string, name: string, subscriptionId: string, location?: string | null, tags?: Record<string, unknown>, };

export type ResourceGroupSummary = { id: string, name: string, subscriptionId: string, 
/**
 * Resolved here so the UI never has to join against the subscription list.
 */
subscriptionName: string, resourceCount: number, findingCount: number, 
/**
 * Resource ids in this group, ordered by name then id.
 */
resourceIds: Array<string>, };

export type Resource = { id: string, displayId: string, name: string, azureType: string, kind?: string | null, location?: string | null, resourceGroup?: string | null, subscriptionId: string, tags?: Record<string, unknown>, sku?: unknown, identity?: unknown, properties?: Record<string, unknown>, findingCount: number, edgeCount: number, };

export type ResourceType = { azureType: string, displayName: string, count: number, icon: string, color: string, };

export type NameCount = { name: string, count: number, };

export type Finding = { queryName: string, category: string, severity: Severity, resourceId?: string | null, title: string, detail?: unknown, };

export type Edge = { sourceId: string, targetId: string, kind: EdgeKind, properties?: unknown, };

export type QueryRun = { queryName: string, category: string, rowCount?: number | null, durationMs?: number | null, error?: string | null, };

export type QueryDefMeta = { name: string, category: string, kind: QueryKind, description: string, };

export type QueryRows = { queryName: string, columns: Array<string>, rows: Array<Record<string, unknown>>, };

export type TopologyRequest = { snapshotId?: string | null, mode: TopologyMode, scope: TopologyScope, };

export type TopologyMode = { "kind": "estate", 
/**
 * Subscription ids the user has expanded; empty means "auto".
 */
expandedSubscriptions: Array<string>, } | { "kind": "group", groupId: string, } | { "kind": "neighbourhood", resourceId: string, depth: number, 
/**
 * Edge-kind classes to include; empty means all.
 */
kindClasses: Array<string>, };

export type TopologyScope = { 
/**
 * Subscription ids to include; empty means all.
 */
subscriptions: Array<string>, 
/**
 * Azure types to include; empty means all.
 */
azureTypes: Array<string>, showUnconnected: boolean, };

export type TopologyGraph = { level: TopologyLevel, lanes: Array<TopologyLane>, nodes: Array<TopologyNode>, links: Array<TopologyLink>, kindClasses: Array<KindClassCount>, counts: TopologyCounts, };

export type TopologyLane = { subscriptionId: string, name: string, expanded: boolean, groupCount: number, resourceCount: number, findingCount: number, };

export type TopologyNode = { id: string, 
/**
 * resource | resource-group | subscription | vnet | subnet | aggregate
 */
kind: TopologyNodeKind, name: string, subtitle: string, azureType?: string | null, 
/**
 * Subscription id this node belongs to (estate mode lanes).
 */
lane?: string | null, 
/**
 * Containment: a subnet's vnet, a placed resource's subnet.
 */
parentId?: string | null, 
/**
 * core | unconnected — which shelf the group view lays the node in.
 */
zone?: TopologyZone, 
/**
 * BFS distance from the subject in neighbourhood mode.
 */
hop?: number | null, 
/**
 * Members folded or aggregated into this node (resource ids).
 */
memberIds: Array<string>, count: number, findingCount: number, resourceId?: string | null, groupId?: string | null, 
/**
 * Resource groups rolled into an estate-level "unconnected groups" tile.
 * Empty on every other node; `member_ids` still lists their resources.
 */
groupIds: Array<string>, };

export type TopologyLink = { sourceId: string, targetId: string, label: string, kindClass: KindClass, count: number, };

export type KindClassCount = { class: string, count: number, };

export type TopologyCounts = { 
/**
 * Resources (or groups, at estate level) in scope.
 */
total: number, 
/**
 * Drawn as their own node.
 */
drawn: number, 
/**
 * Folded into a host node (NIC into VM, child into parent).
 */
folded: number, 
/**
 * Rolled into ×N aggregate tiles or collapsed lanes.
 */
aggregated: number, 
/**
 * Neighbours in other groups drawn as ghost stubs (group view only).
 */
external: number, 
/**
 * Excluded by the request's filters (never silently — always counted).
 */
hiddenByFilter: number, totalLinks: number, drawnLinks: number, };

export type CollectRequest = { subscriptions: Array<string>, notes?: string | null, };

export type CollectResult = { snapshotId: string, status: string, queriesRun: number, queriesFailed: number, rowsIngested: number, screenshots?: WebsiteBatchResult | null, };

export type CollectionStage = "inventory" | "discovery" | "capture";

export type CollectionQueryProgress = { completed: number, total: number, rows: number, failed: number, latestQuery?: string | null, };

export type CollectionEvent = { "event": "stage", "data": { stage: CollectionStage, } } | { "event": "queries", "data": { progress: CollectionQueryProgress, } } | { "event": "phase", "data": { message: string, } } | { "event": "complete", "data": { snapshotId: string, } } | { "event": "failed", "data": { message: string, } } | { "event": "screenshots", "data": { progress: WebsiteProgress, } };

export type WebsiteState = { endpoints: Array<WebsiteEndpoint>, captures: Array<WebsiteCapture>, evidenceErrors: Array<string>, };

export type WebsiteEndpoint = { resourceId: string, resourceName: string, source: string, hostname?: string | null, url?: string | null, status: 'ready' | 'disabled' | 'wildcard' | 'missing_hostname' | 'invalid_hostname' | 'missing_evidence', };

export type WebsiteCapture = { url: string, finalUrl?: string | null, capturedAt?: string | null, attemptedAt: string, status: 'running' | 'captured' | 'failed' | 'cancelled' | 'interrupted', error?: string | null, renderer?: string | null, width?: number | null, height?: number | null, };

export type WebsiteCaptureRequest = { snapshotId: string, urls: Array<string>, retryOnly: boolean, };

export type WebsiteProgress = { completed: number, total: number, url?: string | null, captured: number, failed: number, cancelled: boolean, };

export type WebsiteBatchResult = { captured: number, failed: number, skipped: number, cancelled: boolean, error?: string | null, };

export type ExportRequest = { includeReference?: boolean | null, snapshotId: string, destination: string, exportKind: ExportKind, formats: Array<string>, diagramType?: string | null, subscriptionId?: string | null, resourceGroup?: string | null, };

export type ExportResult = { destination: string, outputs: Array<string>, };

export type ExportEvent = { "event": "phase", "data": { message: string, } } | { "event": "complete", "data": { outputCount: number, } } | { "event": "failed", "data": { message: string, } };

