import type {
  AppBootstrap,
  ConnectionCheck,
  SettingsDocumentDto,
  SettingsValues,
} from "./types";
import { mockBootstrap } from "./mock-data";

const tenantId = "11111111-1111-4111-8111-111111111111";
export const previewSettings: SettingsDocumentDto = {
  path: mockBootstrap.configPath,
  revision: "preview",
  legacy: false,
  error: null,
  legacyTenantId: null,
  legacyClientId: null,
  check: null,
  values: {
    schema_version: 2,
    cloud: "public",
    default_tenant: "contoso",
    tenants: {
      contoso: {
        name: "Contoso",
        tenant_id: tenantId,
        client_id: "22222222-2222-4222-8222-222222222222",
        secret_ref: "33333333-3333-4333-8333-333333333333",
        collect: {},
        audit: { required_tags: ["environment", "owner", "cost-centre"] },
        branding: { company: "Contoso" },
      },
      northwind: {
        name: "Northwind Traders",
        tenant_id: "44444444-4444-4444-8444-444444444444",
        client_id: "55555555-5555-4555-8555-555555555555",
        secret_env: "AZDOCS_NORTHWIND_SECRET",
        collect: {},
        audit: {},
        branding: {},
      },
    },
    collect: {
      subscriptions: [],
      concurrency: 4,
      retry: {
        max_attempts: 5,
        base_delay_ms: 500,
        max_delay_secs: 60,
        timeout_secs: 120,
        connect_timeout_secs: 15,
      },
    },
    audit: { required_tags: ["environment", "owner"] },
    storage: { db_path: mockBootstrap.databasePath },
    branding: {
      company: "",
      title: "Azure Estate Report",
      subtitle: "",
      primary_color: "#0078d4",
      accent_color: "#4da3e8",
      logo: null,
      page_size: "a4",
      margin: "2cm",
      footer: "Generated by azdocs.",
      theme: "field-report",
      labels: "en",
      font_family: "",
      mono_family: "",
      font_dir: null,
    },
  },
};
export const previewCheck: ConnectionCheck = {
  checkedAt: "2026-09-13T12:00:00Z",
  subscriptions: [
    { id: "66666666-6666-4666-8666-666666666666", name: "Contoso production" },
  ],
  inaccessibleSubscriptions: [],
  verdict: "broader_grants",
  grants: [
    {
      scope: "/subscriptions/66666666-6666-4666-8666-666666666666",
      role: "Contributor",
      roleId: "b24988ac-6180-42a0-ab88-20f7382dd24c",
      verdict: "broader_grants",
      actions: ["*"],
    },
  ],
  issues: [],
};
export function savePreview(values: SettingsValues): AppBootstrap {
  previewSettings.values = structuredClone(values);
  mockBootstrap.tenants = Object.entries(values.tenants).map(
    ([reference, p]) => ({
      reference,
      name: p.name,
      tenantId: p.tenant_id,
      configured: true,
    }),
  );
  return structuredClone(mockBootstrap);
}
export function selectPreviewTenant(id: string): AppBootstrap {
  return {
    ...structuredClone(mockBootstrap),
    activeTenantId: id,
    snapshots: id === tenantId ? mockBootstrap.snapshots : [],
    latestSnapshotId: id === tenantId ? mockBootstrap.latestSnapshotId : null,
  };
}
