use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::ConfigError;

pub const ENV_TENANT_ID: &str = "AZDOCS_TENANT_ID";
pub const ENV_CLIENT_ID: &str = "AZDOCS_CLIENT_ID";
pub const ENV_CLIENT_SECRET: &str = "AZDOCS_CLIENT_SECRET";

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Config {
    pub auth: AuthConfig,
    pub collect: CollectConfig,
    pub audit: AuditConfig,
    pub storage: StorageConfig,
    pub branding: BrandingConfig,
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct AuthConfig {
    pub tenant_id: Option<String>,
    pub client_id: Option<String>,
    pub client_secret: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct CollectConfig {
    /// Subscription ids to collect; empty means all visible to the credential.
    pub subscriptions: Vec<String>,
    pub concurrency: usize,
}

impl Default for CollectConfig {
    fn default() -> Self {
        Self {
            subscriptions: Vec::new(),
            concurrency: 4,
        }
    }
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct AuditConfig {
    pub required_tags: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct StorageConfig {
    pub db_path: PathBuf,
}

impl Default for StorageConfig {
    fn default() -> Self {
        Self {
            db_path: default_db_path(),
        }
    }
}

/// Look and feel of the exported reports (HTML, PDF, DOCX). The defaults
/// reproduce the unbranded output exactly; every field can be overridden in
/// `[branding]`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct BrandingConfig {
    /// Organisation name shown on covers and footers; empty hides it.
    pub company: String,
    /// Report title (cover page, HTML `<h1>`).
    pub title: String,
    /// Optional subtitle under the title; empty hides it.
    pub subtitle: String,
    /// Main brand color as `#rrggbb` (headings, links, badges).
    pub primary_color: String,
    /// Secondary color as `#rrggbb` (dark-mode links, rules, highlights).
    pub accent_color: String,
    /// Path to a logo image (.png/.jpg/.jpeg/.gif/.svg), relative paths are
    /// resolved against the config file's directory.
    pub logo: Option<PathBuf>,
    /// PDF paper size (a Typst paper name, e.g. "a4" or "us-letter").
    pub page_size: String,
    /// PDF page margin (a Typst length, e.g. "2cm" or "1in").
    pub margin: String,
    /// Footer text on every report page.
    pub footer: String,
    /// Document theme: a file stem from `data/themes/` or from
    /// `<config dir>/azdocs/themes/`. An unknown name lists the valid ones.
    pub theme: String,
    /// Wording set: a file stem from `data/labels/` or from
    /// `<config dir>/azdocs/labels/`. An unknown name lists the valid ones.
    pub labels: String,
    /// Overrides the theme's `typography.sans` for the PDF and HTML; the
    /// family must be vendored or supplied via `font_dir`. Empty keeps it.
    pub font_family: String,
    /// Overrides the theme's `typography.mono`; empty keeps it.
    pub mono_family: String,
    /// Directory of extra `.ttf`/`.otf` faces loaded into the PDF font book,
    /// so a corporate typeface can be used without vendoring it. Relative
    /// paths resolve against this config file's directory.
    pub font_dir: Option<PathBuf>,
}

impl Default for BrandingConfig {
    fn default() -> Self {
        Self {
            company: String::new(),
            title: "Azure Estate Report".to_owned(),
            subtitle: String::new(),
            // The pre-branding hard-coded palette: Azure blue with the
            // lighter dark-mode link blue from the docs site.
            primary_color: "#0078d4".to_owned(),
            accent_color: "#4da3e8".to_owned(),
            logo: None,
            page_size: "a4".to_owned(),
            margin: "2cm".to_owned(),
            footer: "Generated by azdocs.".to_owned(),
            theme: crate::report::theme::DEFAULT_THEME.to_owned(),
            labels: crate::labels::DEFAULT_LABELS.to_owned(),
            font_family: String::new(),
            mono_family: String::new(),
            font_dir: None,
        }
    }
}

/// Platform data dir (e.g. `~/Library/Application Support/azdocs` on macOS,
/// `~/.local/share/azdocs` on Linux), falling back to the cwd.
pub fn default_db_path() -> PathBuf {
    directories::ProjectDirs::from("", "", "azdocs")
        .map(|dirs| dirs.data_dir().join("azdocs.db"))
        .unwrap_or_else(|| PathBuf::from("azdocs.db"))
}

/// Platform config file location (e.g. `~/.config/azdocs/azdocs.toml` on
/// Linux); `azdocs init` writes here unless `--config` overrides it.
pub fn default_config_path() -> PathBuf {
    directories::ProjectDirs::from("", "", "azdocs")
        .map(|dirs| dirs.config_dir().join("azdocs.toml"))
        .unwrap_or_else(|| PathBuf::from("azdocs.toml"))
}

/// Credentials with all required values present, ready for token acquisition.
#[derive(Debug, Clone)]
pub struct Credentials {
    pub tenant_id: String,
    pub client_id: String,
    pub client_secret: String,
}

impl Config {
    /// Load config from an explicit path, or search `./azdocs.toml` then the
    /// platform config dir. Environment variables override file values.
    pub fn load(explicit: Option<&Path>) -> Result<Self, ConfigError> {
        Ok(Self::load_with_source(explicit)?.0)
    }

    /// Like [`Config::load`], but also reports which file (if any) the config
    /// came from, so relative paths inside it (e.g. `branding.logo`) can be
    /// resolved against its directory.
    pub fn load_with_source(
        explicit: Option<&Path>,
    ) -> Result<(Self, Option<PathBuf>), ConfigError> {
        let (mut config, source) = match explicit {
            Some(path) => (Self::from_file(path)?, Some(path.to_path_buf())),
            None => {
                let candidates = Self::default_paths();
                match candidates.iter().find(|p| p.exists()) {
                    Some(path) => (Self::from_file(path)?, Some(path.clone())),
                    None => (Self::default(), None),
                }
            }
        };
        config.apply_env_overrides();
        Ok((config, source))
    }

    pub fn from_file(path: &Path) -> Result<Self, ConfigError> {
        let raw = std::fs::read_to_string(path).map_err(|source| ConfigError::Read {
            path: path.to_path_buf(),
            source,
        })?;
        toml::from_str(&raw).map_err(|source| ConfigError::Parse {
            path: path.to_path_buf(),
            source: Box::new(source),
        })
    }

    pub fn default_paths() -> Vec<PathBuf> {
        let mut paths = vec![PathBuf::from("azdocs.toml")];
        if let Some(dirs) = directories::ProjectDirs::from("", "", "azdocs") {
            paths.push(dirs.config_dir().join("azdocs.toml"));
        }
        paths
    }

    fn apply_env_overrides(&mut self) {
        for (var, field) in [
            (ENV_TENANT_ID, &mut self.auth.tenant_id),
            (ENV_CLIENT_ID, &mut self.auth.client_id),
            (ENV_CLIENT_SECRET, &mut self.auth.client_secret),
        ] {
            if let Ok(value) = std::env::var(var)
                && !value.is_empty()
            {
                *field = Some(value);
            }
        }
    }

    /// Resolve complete credentials or say exactly what is missing and how to set it.
    pub fn credentials(&self) -> Result<Credentials, ConfigError> {
        let tenant_id = self
            .auth
            .tenant_id
            .clone()
            .ok_or(ConfigError::MissingValue("auth.tenant_id", ENV_TENANT_ID))?;
        let client_id = self
            .auth
            .client_id
            .clone()
            .ok_or(ConfigError::MissingValue("auth.client_id", ENV_CLIENT_ID))?;
        let client_secret = self
            .auth
            .client_secret
            .clone()
            .ok_or(ConfigError::MissingValue(
                "auth.client_secret",
                ENV_CLIENT_SECRET,
            ))?;
        Ok(Credentials {
            tenant_id,
            client_id,
            client_secret,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_file_parses_full_config() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("azdocs.toml");
        std::fs::write(
            &path,
            r#"
[auth]
tenant_id = "t"
client_id = "c"
client_secret = "s"

[collect]
subscriptions = ["sub1"]
concurrency = 8

[audit]
required_tags = ["owner"]

[storage]
db_path = "estate.db"
"#,
        )
        .unwrap();

        let config = Config::from_file(&path).unwrap();

        assert_eq!(config.collect.concurrency, 8);
    }

    #[test]
    fn from_file_rejects_unknown_fields() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("azdocs.toml");
        std::fs::write(&path, "[auth]\ntenant = \"typo\"\n").unwrap();

        let result = Config::from_file(&path);

        assert!(matches!(result, Err(ConfigError::Parse { .. })));
    }

    #[test]
    fn unit_branding_defaults_reproduce_current_look() {
        let branding = BrandingConfig::default();

        assert_eq!(branding.title, "Azure Estate Report");
        assert_eq!(branding.primary_color, "#0078d4");
        assert_eq!(branding.accent_color, "#4da3e8");
        assert_eq!(branding.footer, "Generated by azdocs.");
        assert_eq!(branding.theme, "field-report");
        assert_eq!(branding.labels, "en");
        assert!(branding.logo.is_none());
        assert_eq!(branding.page_size, "a4");
        assert_eq!(branding.margin, "2cm");
    }

    #[test]
    fn unit_branding_rejects_unknown_field_when_typoed() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("azdocs.toml");
        std::fs::write(&path, "[branding]\ncolour = \"#123456\"\n").unwrap();

        let result = Config::from_file(&path);

        assert!(matches!(result, Err(ConfigError::Parse { .. })));
    }

    #[test]
    fn unit_branding_parses_overrides_when_present() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("azdocs.toml");
        std::fs::write(
            &path,
            "[branding]\ncompany = \"Contoso\"\nprimary_color = \"#112233\"\n",
        )
        .unwrap();

        let config = Config::from_file(&path).unwrap();

        assert_eq!(config.branding.company, "Contoso");
        assert_eq!(config.branding.primary_color, "#112233");
        // Untouched fields keep their defaults.
        assert_eq!(config.branding.title, "Azure Estate Report");
    }

    #[test]
    fn credentials_reports_missing_tenant() {
        let config = Config::default();

        let err = config.credentials().unwrap_err();

        assert!(err.to_string().contains("auth.tenant_id"));
    }
}
