#!/usr/bin/env python3
"""Regenerate data/azure2_stencils.toml from draw.io's bundled shape library.

The draw.io emitter references stencils by path — `img/lib/azure2/<category>/
<Name>.svg` — and draw.io renders a path it cannot resolve as a broken-image
placeholder rather than failing. A wrong category therefore ships silently;
`microsoft.web/staticsites` pointed at `app_services` instead of `preview` and
nobody noticed until it appeared in a workbook.

The manifest this writes is what `icons.rs` checks its mappings against, so a
bad path fails `cargo test` with no draw.io installed. It also carries each
stencil's native aspect, because they are not square — a virtual network is
18.0 x 10.8 — and a container's header cell is cut to that ratio.

Usage:
    python3 data/tools/build_azure2_manifest.py [--asar PATH] [--check]

`--check` verifies the checked-in manifest is current and exits non-zero if
not, which is the form to run when draw.io has been upgraded.
"""

from __future__ import annotations

import argparse
import json
import re
import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MANIFEST = REPO / "data" / "azure2_stencils.toml"

# Where the desktop app keeps its bundle on each platform.
CANDIDATES = [
    Path("/Applications/draw.io.app/Contents/Resources/app.asar"),
    Path("/opt/drawio/resources/app.asar"),
    Path("/usr/lib/drawio/resources/app.asar"),
    Path.home() / "AppData/Local/Programs/draw.io/resources/app.asar",
]

ASAR_PATH = ["drawio", "src", "main", "webapp", "img", "lib", "azure2"]

HEADER = """\
# draw.io's bundled azure2 stencil library: every path the diagram emitter may
# reference, and the aspect (width / height) each stencil ships at.
#
# GENERATED by data/tools/build_azure2_manifest.py — do not edit by hand.
# Re-run it after upgrading draw.io; `--check` reports whether this is stale.
#
# draw.io renders an unresolvable image path as a broken-image placeholder
# rather than failing, so a wrong category ships silently. `icons.rs` tests its
# mappings against this file to make that a build failure instead.

"""


def find_asar(explicit: str | None) -> Path:
    if explicit:
        path = Path(explicit)
        if not path.is_file():
            sys.exit(f"no asar archive at {path}")
        return path
    for candidate in CANDIDATES:
        if candidate.is_file():
            return candidate
    sys.exit(
        "could not find draw.io's app.asar in any known location; "
        "pass --asar PATH (the app must be installed to regenerate this)"
    )


def read_directory(handle) -> tuple[dict, int]:
    """The asar header is a JSON directory tree behind four uint32 fields."""
    _, _, _, json_len = struct.unpack("<IIII", handle.read(16))
    tree = json.loads(handle.read(json_len).split(b"\x00")[0].decode("utf-8"))
    return tree, handle.tell()


def descend(tree: dict, path: list[str]) -> dict:
    node = tree["files"]
    for part in path:
        entry = node.get(part)
        if entry is None:
            sys.exit(f"no {'/'.join(path)} inside the archive (draw.io layout changed?)")
        node = entry.get("files", entry)
    return node


def aspect_of(svg: str) -> float | None:
    """Width over height, from the viewBox if present and the attributes if not."""
    box = re.search(r'viewBox="\s*[\d.eE+-]+\s+[\d.eE+-]+\s+([\d.eE+-]+)\s+([\d.eE+-]+)', svg)
    if box:
        width, height = float(box.group(1)), float(box.group(2))
    else:
        w = re.search(r'\swidth="([\d.]+)(?:px)?"', svg)
        h = re.search(r'\sheight="([\d.]+)(?:px)?"', svg)
        if not (w and h):
            return None
        width, height = float(w.group(1)), float(h.group(1))
    if width <= 0 or height <= 0:
        return None
    return width / height


def build(asar: Path) -> str:
    with asar.open("rb") as handle:
        tree, body = read_directory(handle)
        azure2 = descend(tree, ASAR_PATH)

        rows: list[tuple[str, float]] = []
        skipped: list[str] = []
        for category in sorted(azure2):
            files = azure2[category].get("files", {})
            for name in sorted(files):
                if not name.endswith(".svg"):
                    continue
                entry = files[name]
                handle.seek(body + int(entry["offset"]))
                svg = handle.read(entry["size"]).decode("utf-8", "replace")
                aspect = aspect_of(svg)
                stencil = f"{category}/{name[:-4]}"
                if aspect is None:
                    skipped.append(stencil)
                    continue
                rows.append((stencil, aspect))

    if skipped:
        print(f"note: {len(skipped)} stencils carry no usable size and were skipped",
              file=sys.stderr)
        for stencil in skipped[:5]:
            print(f"      {stencil}", file=sys.stderr)

    lines = [HEADER, "[stencils]\n"]
    lines += [f'"{stencil}" = {aspect:.4f}\n' for stencil, aspect in rows]
    print(f"{len(rows)} stencils across "
          f"{len({s.split('/')[0] for s, _ in rows})} categories", file=sys.stderr)
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--asar", help="path to draw.io's app.asar")
    parser.add_argument("--check", action="store_true",
                        help="fail if the checked-in manifest is stale")
    args = parser.parse_args()

    content = build(find_asar(args.asar))
    if args.check:
        current = MANIFEST.read_text(encoding="utf-8") if MANIFEST.exists() else ""
        if current != content:
            print(f"{MANIFEST.relative_to(REPO)} is stale — re-run without --check",
                  file=sys.stderr)
            return 1
        print(f"{MANIFEST.relative_to(REPO)} is current")
        return 0

    MANIFEST.write_text(content, encoding="utf-8")
    print(f"wrote {MANIFEST.relative_to(REPO)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
